package: terminal
version: '0.1.0'
author: 'skerbis'
supportpage: https://github.com/KLXM/terminal
page:
    title: Terminal
    popup: true
    perm: admin
    live_mode: false
    hasLayout: false
    icon: rex-icon fa-terminal
    linkAttr: { class: 'terminal-link' }
requires:
    redaxo: '^5.16.1'
    php:
        version: '>=8.2, <9'
