package: terminal
version: '0.0.1'
author: 'skerbis'
supportpage: https://github.com/skerbis/terminal
page:
    title: Terminal
    popup: true
    perm: admin
    live_mode: false
    hasLayout: false
    icon: rex-icon fa-prompt
    linkAttr: { class: rex-popup }
requires:
    redaxo: '^5.16.1'
    php:
        version: '>=8.2, <9'
